~/testbed/dm_test $ rake dm:db:database_yaml
(in /Users/jdempsey/testbed/dm_test)
/Users/jdempsey/testbed/dm_test/config/init.rb:1: warning: already initialized constant KCODE
 ~ Loaded DEVELOPMENT Environment...
 ~ loading gem 'merb_datamapper' ...
 ~ loading gem 'dm-core' ...
 ~ loading gem 'merb_datamapper' ...
 ~ Merb::Orms::DataMapper::Connect block.
 ~ No database.yml file found in /Users/jdempsey/testbed/dm_test/config, assuming database connection(s) established in the environment file in /Users/jdempsey/testbed/dm_test/config/environments
 ~ Checking if we need to use DataMapper sessions
 ~ Merb::Orms::DataMapper::Connect complete
 ~ Compiling routes...
 ~ Starting Merb server listening at 0.0.0.0:4000
