name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.8

      # 🔥 VERY IMPORTANT (Fix your error)
      - name: Clean Gradle Cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper

      - name: Flutter Clean
        run: flutter clean

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
