name: Initialize Flutter Project

on:
  workflow_dispatch: # Yeh humein manual chalane ki permission dega

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Files
        run: |
          # Pehle se maujood files ko safe rakho
          mkdir temp_lib
          cp -r lib/* temp_lib/
          cp pubspec.yaml temp_pubspec.yaml
          
          # Naya project create karo usi jagah
          rm -rf *
          flutter create --org com.rawat . --project-name pharoah_erp
          
          # Purani files wapas dalo
          rm -rf lib/*
          cp -r temp_lib/* lib/
          cp temp_pubspec.yaml pubspec.yaml
          rm -rf temp_lib temp_pubspec.yaml

      - name: Commit Files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Initialize Android and iOS system files"
          git push
